name: Website Backend Deployment

on:
  push:
    branches: [ "main" ]
    paths:
      - 'backend/**'
  
  workflow_dispatch:

env:
  AZURE_FUNCTIONAPP_NAME: 'VisitFunc'
  AZURE_FUNCTIONAPP_PACKAGE_PATH: 'backend'
  PYTHON_VERSION: '3.11'
  WORKING_DIRECTORY: '.'
  STARTUP_COMMAND: ''

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: azure/login@v2
        with:
          creds: '${{ secrets.AZURE_CREDENTIALS }}'

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: python install
        working-directory: ${{ env.WORKING_DIRECTORY }}
        run: |
           sudo apt install python${{ env.PYTHON_VERSION }}-venv
           python -m venv --copies antenv
           source antenv/bin/activate
           pip install setuptools
           pip install -r requirements.txt
      
      - uses: azure/webapps-deploy@v2
        with:
            app-name: ${{ env.AZURE_FUNCTIONAPP_NAME }}
            package: ${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}
            startup-command: ${{ env.STARTUP_COMMAND }}
      
      
      
            
            
      