name: Website Backend Deployment

on:
  push:
    branches: [ "main" ]
    paths:
      - 'backend/**'
  
  workflow_dispatch:

env:
  AZURE_FUNCTIONAPP_NAME: 'VisitFunc'
  AZURE_FUNCTIONAPP_PACKAGE_PATH: 'backend'
  PYTHON_VERSION: '3.11'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: azure/login@v2
        with:
          creds: '${{ secrets.AZURE_CREDENTIALS }}'

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: 'Resolve Project Dependencies Using Pip'
        shell: bash
        run: |
            pushd './${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}'
            python -m pip install --upgrade pip
            pip install -r requirements.txt --target=".python_packages/lib/site-packages"
            pip install azure-functions
            pip install azure-cosmos
            pip install pytest
            popd
    
      - name: Run Unit Test
        shell: bash
        run: |
            pushd './${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}/${{env.AZURE_FUNCTIONAPP_NAME}}'
            pytest -v -s
    
      - name: 'Run Azure Functions Action'
        uses: Azure/functions-action@v1
        id: fa
        with:
            app-name: ${{ env.AZURE_FUNCTIONAPP_NAME }}
            package: '${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}/${{env.AZURE_FUNCTIONAPP_NAME}}'
            #publish-profile: ${{ secrets.AZURE_FUNCTIONAPP_PUBLISH_PROFILE }}
            scm-do-build-during-deployment: true
            enable-oryx-build: true
      