name: Website Frontend Deployment

on:
  push:
    branches: [ "main" ]
    paths:
      - 'frontend/**'
  
  workflow_dispatch:


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: azure/login@v2
        with:
          creds: '${{ secrets.AZURE_CREDENTIALS }}'

      
      - name: Upload to blob storage
        uses: azure/CLI@v1
        with:
          inlineScript: |
            az storage blob upload-batch --account-name ${{vars.storageName}} --auth-mode key -d '$web' -s ./frontend --overwrite

      - name: Purge CDN
        uses: azure/CLI@v1
        with:
          inlineScript: |
           az cdn endpoint purge --content-paths  "/*" --profile-name ${{vars.profileName}} --name "familywebsite" --resource-group ${{vars.rgName}}

      - name: AZ Logout
        run: |
          az logout
        if: always()