name: Infrastructure Deployment

on:
    push:
        branches: ["main"]
        paths:
            - 'infrastructure/**'
    workflow_dispatch:

env:
    location: eastus
    appName: familywebsite
    environ: dev

jobs:
    create-rg:
        runs-on: ubuntu-latest
        outputs:
            rgName: ${{ steps.rg.outputs.rgName }}
            actualAppName: ${{steps.rg.outputs.actualAppName}}
        steps:
            - name: Checkout repository
              uses: actions/checkout@v4

            - name: Log in with Azure
              uses: azure/login@v2
              with:
                creds: '${{ secrets.AZURE_CREDENTIALS }}'
                
            
            - name: Create rg
              id: rg
              uses: azure/arm-deploy@v2
              with:
                 scope: subscription
                 subscriptionId: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
                 region: ${{ env.location }}
                 template: ./infrastructure/create_rg.json
                 parameters: appName=${{env.appName}} environment=${{env.environ}} location=${{env.location}}


