name: Infrastructure Deployment

on:
    push:
        branches: ["main"]
        paths:
            - 'infrastructure/**'
    workflow_dispatch:

env:
    location: eastus
    appName: familywebsite
    environ: dev
    domainName: 'thehodgesfamily.net'
    
jobs:
    create-rg:
        runs-on: ubuntu-latest
        outputs:
            rgName: ${{ steps.rg.outputs.rgName }}
            actualAppName: ${{steps.rg.outputs.actualAppName}}
        steps:
            - name: Checkout repository
              uses: actions/checkout@v4

            - name: Log in with Azure
              uses: azure/login@v2
              with:
                creds: '${{ secrets.AZURE_CREDENTIALS }}'
                
            
            - name: Create rg
              id: rg
              uses: azure/arm-deploy@v2
              with:
                 scope: subscription
                 subscriptionId: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
                 region: ${{ env.location }}
                 template: ./infrastructure/create_rg.json
                 parameters: appName=${{env.appName}} environment=${{env.environ}} location=${{env.location}}

    create-storage:
        runs-on: ubuntu-latest
        needs: create-rg
        outputs:
            storageName: ${{steps.storage.outputs.storageName}}
            storageWebEndpoint: ${{steps.storage.outputs.storageWebEndpoint}}
        steps:
        - name: Checkout repository
          uses: actions/checkout@v4

        - name: Log in with Azure
          uses: azure/login@v2
          with:
             creds: '${{secrets.AZURE_CREDENTIALS}}'

        - name: Create Storage
          uses: azure/arm-deploy@v2
          id: storage
          with:
            scope: resourcegroup
            resourceGroupName: ${{ needs.create-rg.outputs.rgName }}
            template: ./infrastructure/create_storage.json
            parameters: appName=${{env.appName}} environment=${{env.environ}}

    create-cdn:
        runs-on: ubuntu-latest
        needs: [create-rg,create-storage]
        outputs:
            profileName: ${{steps.cdn.outputs.profileName}}
            customDomainName: ${{steps.cdn.outputs.customDomainName}}
            endpointName: ${{steps.cdn.outputs.endpointName}}
        steps:
        - name: Checkout repository
          uses: actions/checkout@v4

        - name: Log in with Azure
          uses: azure/login@v2
          with:
            creds: '${{secrets.AZURE_CREDENTIALS}}'

        - name: Create CDN
          uses: azure/arm-deploy@v2
          id: cdn
          with:
            scope: resourcegroup
            resourceGroupName: ${{needs.create-rg.outputs.rgName}}
            template: ./infrastructure/create_cdn.json
            parameters: appName=${{env.appName}} environment=${{env.environ}} domainName=${{env.domainName}} storageWebEndpoint=${{needs.create-storage.outputs.storageWebEndpoint}}
